name: BloodFX-3.0.0
version: 7WDEV
main: StockPE\Blood
api: [3.0.0]
author: 7awariGamer(7Wdev)

description: hi , this a fixed plugin for new pmmp (api : 3.0.0) ! this plugin adds blood effect while hitting in minecraft pe servers!
